export const initialState = {
  posts: {
    data: [
      {
        id: '1',
        title: 'Looking for new job?',
        publicationDate: '01.01.2021',
        updateDate: '10.01.2021',
        email: 'email@example.com',
        status: 'published',
        photo: 'https://images.pexels.com/photos/355952/pexels-photo-355952.jpeg',
      },
      {
        id: '2',
        title: 'Looking for new job?',
        publicationDate: '01.01.2021',
        updateDate: '10.01.2021',
        email: 'johnDoe@email.com',
        status: 'published',
        photo: 'https://images.pexels.com/photos/355952/pexels-photo-355952.jpeg',
      },
      {
        id: '3',
        title: 'Looking for new job?',
        publicationDate: '01.01.2021',
        updateDate: '10.01.2021',
        email: 'email@example.com',
        status: 'published',
        photo: 'https://images.pexels.com/photos/355952/pexels-photo-355952.jpeg',
      },
      {
        id: '4',
        title: 'Looking for new job?',
        publicationDate: '01.01.2021',
        updateDate: '10.01.2021',
        email: 'johnDoe@email.com',
        status: 'published',
        photo: 'https://images.pexels.com/photos/355952/pexels-photo-355952.jpeg',
      },
      {
        id: '5',
        title: 'Looking for new job?',
        publicationDate: '01.01.2021',
        updateDate: '10.01.2021',
        email: 'email@example.com',
        status: 'published',
        photo: 'https://images.pexels.com/photos/355952/pexels-photo-355952.jpeg',
      },
      {
        id: '6',
        title: 'Looking for new job?',
        publicationDate: '01.01.2021',
        updateDate: '10.01.2021',
        email: 'johndoe@example.com',
        status: 'published',
        photo: 'https://images.pexels.com/photos/355952/pexels-photo-355952.jpeg',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  user: null,
};
